// 单屏控制台样稿（console.html）的演示数据。数值只为看版式，不代表协议或数值设计。
window.CONSOLE_DATA = {
  account: { name: 'xiling', agentOnline: true, connected: true },
  cities: [
    { id: 'c1', name: '襄阳', short: '襄', level: 9, x: 132, y: 88, main: true },
    { id: 'c2', name: '新野', short: '新', level: 5, x: 126, y: 93 },
    { id: 'c3', name: '宛城', short: '宛', level: 3, x: 140, y: 81, famous: true },
  ],
  resources: [
    { key: 'gold', label: '金', value: 182400, rate: 900, cap: 1000000 },
    { key: 'food', label: '粮', value: 41200, rate: -120, cap: 52000 },
    { key: 'wood', label: '木', value: 33100, rate: 980, cap: 36000 },
    { key: 'stone', label: '石', value: 18640, rate: 410, cap: 40000 },
    { key: 'iron', label: '铁', value: 9230, rate: 260, cap: 30000 },
  ],
  population: { current: 4820, cap: 6050 },
  starveIn: '5时43分',
  truce: '2:14:08',
  alerts: [{ kind: 'npc', text: 'NPC 来袭 · 襄阳', eta: '08:42', level: 6 }],
  buildings: [
    { kind: 'government', name: '官府', short: '府', level: 9, note: '金 +900/h · 野地上限 9' },
    { kind: 'farm', name: '农田', short: '田', level: 12, note: '粮 +1,240/h' },
    { kind: 'lumber_mill', name: '伐木场', short: '木', level: 10, note: '木 +980/h' },
    { kind: 'quarry', name: '采石场', short: '石', level: 8, note: '石 +410/h' },
    { kind: 'iron_mine', name: '铁矿', short: '铁', level: 7, note: '铁 +260/h' },
    { kind: 'house', name: '民房', short: '居', level: 11, note: '人口上限 6,050' },
    { kind: 'barracks', name: '军营', short: '营', level: 11, note: '解锁铁骑兵' },
    { kind: 'warehouse', name: '仓库', short: '仓', level: 9, note: '每项保护 9,000' },
    { kind: 'wall', name: '城墙', short: '城', level: 10, note: '守城减伤 50%' },
    { kind: 'academy', name: '书院', short: '学', level: 6, note: '科技上限 Lv6' },
    { kind: 'parade_ground', name: '校场', short: '校', level: 5, note: '在外 3 / 5 支', busy: true },
    { kind: 'beacon', name: '烽火台', short: '烽', level: 4, note: '预警 +40% · 兵种范围' },
    { kind: 'post_station', name: '驿站', short: '驿', level: 0, note: '未建造' },
    { kind: 'arrow_tower', name: '箭塔', short: '塔', level: 3, note: '伤害 450 · 射程 60' },
    { kind: 'tavern', name: '酒馆', short: '馆', level: 4, note: '武将上限 3' },
  ],
  buildQueue: [
    { name: '校场', from: 5, to: 6, left: '00:42:15', pct: 38, by: 'Agent' },
    { name: '城墙', from: 10, to: 11, left: '排队', pct: 0, by: '玩家' },
  ],
  troops: [
    { kind: 'porter', name: '民夫', home: 120, out: 40, unlocked: true },
    { kind: 'militia', name: '义兵', home: 860, out: 300, unlocked: true },
    { kind: 'scout', name: '斥候', home: 45, out: 5, unlocked: true },
    { kind: 'pikeman', name: '长枪兵', home: 420, out: 120, unlocked: true, tag: '克骑' },
    { kind: 'swordsman', name: '刀盾兵', home: 380, out: 200, unlocked: true, tag: '挡箭' },
    { kind: 'archer', name: '弓箭兵', home: 510, out: 150, unlocked: true, tag: '射程 70' },
    { kind: 'cavalry', name: '轻骑兵', home: 160, out: 60, unlocked: true },
    { kind: 'iron_cavalry', name: '铁骑兵', home: 20, out: 0, unlocked: true, tag: '重装' },
    { kind: 'supply_wagon', name: '辎重车', home: 12, out: 4, unlocked: true, tag: '负重 5000' },
    { kind: 'ballista', name: '床弩', home: 30, out: 0, unlocked: true, tag: '射程 95' },
    { kind: 'siege_ram', name: '冲车', home: 0, out: 0, unlocked: false, tag: '军营 8' },
  ],
  recruitQueue: [{ name: '弓箭兵', count: 60, left: '00:06:20', pct: 72 }],
  techs: [
    { name: '农耕', level: 5, effect: '四资源产量 +25%' },
    { name: '负重', level: 3, effect: '负重 +15%' },
    { name: '行军', level: 4, effect: '行军速度 +20%', researching: '00:18:02' },
    { name: '储存', level: 2, effect: '储量上限 +10%' },
    { name: '侦察', level: 3, effect: '情报：兵种近似' },
    { name: '城防', level: 1, effect: '守城减伤 +1%' },
  ],
  heroes: [
    { name: '张角', famous: true, level: 6, lead: 61, might: 52, wit: 64, state: '城守 · 襄阳' },
    { name: '赵武', level: 4, lead: 32, might: 38, wit: 14, state: '出征 · 截击商队' },
    { name: '李衡', level: 2, lead: 18, might: 22, wit: 35, state: '城内' },
    { name: '孙策', level: 1, lead: 12, might: 29, wit: 11, state: '重伤 01:12' },
  ],
  tavern: [
    { name: '周平', lead: 28, might: 31, wit: 19, cost: 2060 },
    { name: '韩茂', lead: 15, might: 12, wit: 38, cost: 1800 },
    { name: '吕安', lead: 36, might: 20, wit: 22, cost: 2060 },
  ],
  territory: [
    { pos: '128,85', terrain: '森林', level: 6, bonus: '木 +320/h', cluster: '连片 3 · +10%' },
    { pos: '129,85', terrain: '森林', level: 5, bonus: '木 +280/h', cluster: '连片 3 · +10%' },
    { pos: '129,86', terrain: '森林', level: 4, bonus: '木 +240/h', cluster: '连片 3 · +10%' },
    { pos: '135,90', terrain: '金矿', level: 3, bonus: '金 +300/h', cluster: '' },
    { pos: '137,84', terrain: '丘陵', level: 5, bonus: '石 +260/h', cluster: '' },
    { pos: '131,92', terrain: '草原', level: 2, bonus: '粮 +150/h', cluster: '' },
    { pos: '126,89', terrain: '平原', level: 4, bonus: '粮 +210/h', cluster: '' },
  ],
  marches: [
    { title: '截击 运粮商队 Lv4', who: '赵武 · 骑 160', state: '埋伏中', eta: '04:12', pct: 80 },
    { title: '掠夺 野地 Lv6 (138,86)', who: '弓 150 · 刀 200', state: '行军', eta: '01:05', pct: 45 },
    { title: '运输 → 新野', who: '辎重 4 · 粮 12,000', state: '返程', eta: '02:40', pct: 20 },
  ],
  reports: [
    { title: '掠夺 野地 Lv5 森林', result: '胜', detail: '得木 3,750 · 损 12', time: '17:04' },
    { title: '截击 流寇 Lv3', result: '扑空', detail: '目标已走远', time: '16:40' },
    { title: 'NPC 袭击 襄阳', result: '守住', detail: '箭塔 1,350 伤害', time: '16:12' },
    { title: '侦察 名城 宛城', result: '情报', detail: '城守阶段 · 兵种明细', time: '15:58' },
    { title: '黄巾营地 中', result: '胜', detail: '贡献 +420', time: '15:20' },
    { title: '掠夺 NPC 城 Lv4', result: '败', detail: '残部撤回', time: '14:47' },
  ],
  events: [
    { who: 'Agent', text: '发起校场升级至 Lv6', time: '17:06' },
    { who: '系统', text: '农田产出结算 +1,240 粮', time: '17:00' },
    { who: '玩家', text: '张角任命为襄阳城守', time: '16:52' },
    { who: 'Agent', text: '截击商队：赵武率骑兵出发', time: '16:48' },
    { who: '系统', text: '科技「行军」开始研究', time: '16:30' },
    { who: 'Agent', text: '集市兑换 木 8,000 → 金 2,000', time: '16:21' },
    { who: 'Agent', text: '侦察名城宛城（城守阶段）', time: '15:58' },
    { who: 'Agent', text: '弓箭兵 ×60 加入征兵队列', time: '15:41' },
    { who: 'Agent', text: '黄巾营地·中 出兵清剿', time: '15:12' },
    { who: '系统', text: 'NPC 袭击襄阳：守住，箭塔 1,350 伤害', time: '14:55' },
  ],
  agent: {
    stance: '积极扩张',
    minTroops: 300,
    next: '等校场 Lv6 后再开一支掠夺队',
    plan: '优先打 Lv5–6 森林连片；黄巾大营进攻前把弓兵调回襄阳。',
  },
  broadcasts: [
    '【黄巾之乱】张角老巢已现身 (141,79)，全服可讨伐',
    '玩家 子龙 首次占领金矿 (155,102)',
    '名城 宛城 被 xiling 占领，获名将 张角',
  ],
  yt: { stage: '老巢现身', cleared: 34, total: 40, left: '13:20:00', mine: 1840, rank: 7 },
};
