// English twin of copy-chat.ts (AISLG-138, v51). Every member satisfies the Chinese type.

import type { CHAT_COPY } from './copy-chat';

export const CHAT_COPY_EN = {
  launcher: {
    label: 'Chat',
    open: 'Open chat',
    collapse: 'Collapse',
    unread: (count: number) => `${count} unread`,
    emptyWorld: 'No messages in World yet',
    close: 'Close chat',
  },
  tabs: {
    world: 'World',
    system: 'Server news',
    private: 'Private',
  },
  system: {
    empty: 'No announcements yet',
    readonly: 'Server news is read-only, pushed by the server',
  },
  world: {
    empty: 'Nobody has said anything in World yet — say hi',
    levelHint: (level: number) => `Your main city's Government must be level ${level} or higher to talk in World`,
  },
  conversations: {
    empty: 'No private chats yet. Click a player name in chat, or select another player’s city on the map',
    unread: (count: number) => `${count} unread`,
    blockedTitle: 'Blocked players',
    blockedEmpty: 'No blocked players',
    unblock: 'Unblock',
  },
  thread: {
    empty: 'No messages yet — say hi',
    back: 'Back to conversations',
    title: (name: string) => `Private chat with ${name}`,
  },
  list: {
    older: 'Older',
    loading: 'Loading…',
    loadFailed: 'Failed to load — please try again later',
  },
  composer: {
    placeholder: (max: number) => `Say something (up to ${max} characters)`,
    send: 'Send',
    emoji: 'Emoji',
    insert: 'Insert',
    counter: (count: number, max: number) => `${count}/${max}`,
    channelWorld: 'To World',
    channelPrivate: (name: string) => `Private to ${name}`,
    draftLabel: 'Card',
    draftRemove: 'Remove card',
    sending: 'Sending…',
  },
  insert: {
    tabs: {
      hero: 'Hero',
      report: 'Report',
      city: 'City',
      coord: 'Tile',
    },
    emptyHero: 'No heroes yet',
    emptyReport: 'No battle reports yet',
    emptyCity: 'No cities yet',
    coordX: 'X',
    coordY: 'Y',
    coordHint: 'Whole number from 0 to 999',
    coordInvalid: 'Coordinates must be between 0 and 999',
    coordUse: 'Use this tile',
    pick: 'Pick',
  },
  card: {
    coordTitle: 'Tile',
    coordTile: (terrain: string, kind: string, level: number) =>
      level > 0 ? `${terrain} · ${kind} Lv${level}` : `${terrain} · ${kind}`,
    jump: 'Show on map',
    heroTag: 'Famous',
    heroStats: (lead: number, force: number, wit: number) => `LDR ${lead} · FOR ${force} · INT ${wit}`,
    heroLevel: (level: number) => `Lv${level}`,
    heroDetailTitle: 'Hero details',
    heroDetailNote: 'This is a snapshot from the moment it was sent; later changes to the hero do not affect this message',
    reportTitle: 'Battle report',
    reportVersus: 'vs',
    reportWon: 'Won',
    reportLost: 'Lost',
    reportOpen: 'View report',
    reportLoadFailed: 'Failed to load the report',
    cityTitle: 'City',
    cityOwner: (name: string) => `Owner ${name}`,
    cityLevel: (level: number) => `Government Lv${level}`,
    tileNpc: 'NPC city',
    tileCity: 'Player city',
    tileWild: 'Wilderness',
  },
  player: {
    chat: 'Private chat',
    block: 'Block',
    unblock: 'Unblock',
    blocked: 'Blocked',
  },
  share: {
    coord: 'Share tile',
    city: 'Share city',
    hero: 'Share hero',
    report: 'Share report',
    dm: 'Private chat',
    draftHint: 'The card is in the chat box; add a line if you like, then send',
  },
  errors: {
    CHAT_GOVERNMENT_TOO_LOW: (level: number) => `Your main city's Government must be level ${level} to talk in World`,
    CHAT_MUTED: (until: string) => `Your account is muted until ${until}`,
    CHAT_BLOCKED: 'This player has blocked you; you cannot send private messages',
    CHAT_RATE_LIMITED: (seconds: number) => `Slow down — try again in ${seconds} seconds`,
    INVALID_PARAMS: 'That message is not allowed — check it and try again',
    AGENT_FORBIDDEN: 'Chat is only available to the player',
    NOT_LOGGED_IN: 'Please log in first',
    INTERNAL: 'Server is busy — please try again later',
    generic: 'Failed to send — please try again later',
  },
  offline: 'Connection lost — chat is unavailable',
} satisfies typeof CHAT_COPY;
