// 聊天浮窗的界面文案（AISLG-138，v51）：页签、消息区、输入区、卡片、屏蔽与错误提示。
// 英文孪生见 copy-chat-en.ts（逐成员 satisfies 本文件的类型）。

export const CHAT_COPY = {
  launcher: {
    label: '聊天',
    open: '展开聊天',
    collapse: '收起',
    unread: (count: number) => `${count} 条未读`,
    emptyWorld: '世界频道还没有消息',
    close: '关闭聊天',
  },
  tabs: {
    world: '世界',
    system: '系统播报',
    private: '私聊',
  },
  system: {
    empty: '暂无播报',
    readonly: '系统播报只读，由服务器推送',
  },
  world: {
    empty: '世界频道还没有消息，来打个招呼吧',
    levelHint: (level: number) => `主城官府达到 ${level} 级才能在世界频道发言`,
  },
  conversations: {
    empty: '还没有私聊。点聊天里的玩家名字，或在地图上选中别人的城池即可开始',
    unread: (count: number) => `${count} 条未读`,
    blockedTitle: '屏蔽名单',
    blockedEmpty: '没有屏蔽的玩家',
    unblock: '取消屏蔽',
  },
  thread: {
    empty: '还没有消息，打个招呼吧',
    back: '返回会话列表',
    title: (name: string) => `与 ${name} 的私聊`,
  },
  list: {
    older: '更早',
    loading: '加载中…',
    loadFailed: '加载失败，请稍后再试',
  },
  composer: {
    placeholder: (max: number) => `说点什么（最多 ${max} 字）`,
    send: '发送',
    emoji: '表情',
    insert: '插入',
    counter: (count: number, max: number) => `${count}/${max}`,
    channelWorld: '发到世界',
    channelPrivate: (name: string) => `私聊 ${name}`,
    draftLabel: '卡片',
    draftRemove: '移除卡片',
    sending: '发送中…',
    limit: (max: number) => `已到 ${max} 字上限（表情也算字）`,
  },
  insert: {
    tabs: {
      hero: '武将',
      report: '战报',
      city: '城池',
      coord: '坐标',
    },
    emptyHero: '还没有武将',
    emptyReport: '还没有战报',
    emptyCity: '还没有城池',
    coordX: 'X',
    coordY: 'Y',
    coordHint: '0 到 999 之间的整数',
    coordInvalid: '坐标需在 0 到 999 之间',
    coordUse: '用这个坐标',
    pick: '选这个',
  },
  card: {
    coordTitle: '坐标',
    coordTile: (terrain: string, kind: string, level: number) =>
      level > 0 ? `${terrain} · ${kind} Lv${level}` : `${terrain} · ${kind}`,
    jump: '在地图上查看',
    heroTag: '名将',
    heroStats: (lead: number, force: number, wit: number) => `统 ${lead} · 武 ${force} · 智 ${wit}`,
    heroLevel: (level: number) => `Lv${level}`,
    heroDetailTitle: '武将详情',
    heroDetailNote: '以下是发送那一刻的快照，之后武将变化不影响这条消息',
    reportTitle: '战报',
    reportVersus: 'vs',
    reportWon: '胜',
    reportLost: '负',
    reportOpen: '查看战报',
    reportLoadFailed: '战报加载失败',
    cityTitle: '城池',
    cityOwner: (name: string) => `主人 ${name}`,
    cityLevel: (level: number) => `官府 ${level} 级`,
    tileNpc: 'NPC 城',
    tileCity: '玩家城',
    tileWild: '野地',
  },
  player: {
    chat: '私聊',
    block: '屏蔽',
    unblock: '取消屏蔽',
    blocked: '已屏蔽',
  },
  share: {
    coord: '分享坐标',
    city: '分享城池',
    hero: '分享武将',
    report: '分享战报',
    dm: '私聊',
    draftHint: '卡片已放进聊天输入框，可以加一句话后发送',
  },
  errors: {
    CHAT_GOVERNMENT_TOO_LOW: (level: number) => `主城官府需达到 ${level} 级才能在世界频道发言`,
    CHAT_MUTED: (until: string) => `账号已被禁言，解禁时间 ${until}`,
    CHAT_BLOCKED: '对方已屏蔽你，无法发送私聊',
    CHAT_RATE_LIMITED: (seconds: number) => `发言太快了，${seconds} 秒后再发`,
    INVALID_PARAMS: '内容不符合要求，请检查后再发',
    AGENT_FORBIDDEN: '聊天只能由玩家本人使用',
    NOT_LOGGED_IN: '请先登录',
    INTERNAL: '服务器繁忙，请稍后再试',
    generic: '发送失败，请稍后再试',
  },
  offline: '连接断开，聊天暂不可用',
};
